version: 3.0.3
defaults:
  - scope:
      path: ''
    values:
      layout: default
woopra_config:
  domain: "adfinitas.fr"
  cookie_domain: ".adfinitas.fr"
controles:
  - email
  - telephone
types:
  - champ_libre_court
  - champ_libre_long
  - liste_deroulante
  - choix_unique
  - choix_multiple
  - champ_caché
  - scoring
