array: []
version: 3.0.3
defaults:
  - scope:
      path: ''
    values:
      layout: default
woopra_config:
  domain: "adfinitas.fr"
  cookie_domain: ".adfinitas.fr"
form-to-db_config:
  schema: "adfinitas_cx"
  envoi_base_de_donnée: true
  message_erreur: "Une erreur est survenue, veuillez envoyer un mail à lghionna@adfinitas.fr"
controles:
  - email
  - telephone
types:
  - champ_libre_court
  - champ_libre_long
  - liste_deroulante
  - choix_unique
  - choix_multiple
  - scoring
